### ISSUE TITLE
GQLGen Integeration

### ISSUE THREAD

**Issue by iamtomcat** [jpascal/graphql-upload#1]
I don't know if you've taken a look at GQLGen, just trying to figure out how to integrate with that library.
No worries if you haven't, just figured I'd ask in case you had a good idea.

**Comment by jpascal** [comment]
@iamtomcat I need to learn GQLGen to understand how to integrating. If you had a time, please create the pull request. :)

**Comment by jpascal** [comment]
I was explore GQLGen. They has self handler for requests. I don't have any time for realise custom handler for GQGen. May be in future...
