### ISSUE TITLE
GraphiQL support

### ISSUE THREAD

**Issue by niondir** [jpascal/graphql-upload#3]
As far as I see, this is not a pure middleware but replaces the handler. 

Is there any way to serve the GraphiQL UI?

**Comment by niondir** [comment]
My approach is to use the graphql-go handler for the UI like this:

	graphqlHandlerFunc := func(w http.ResponseWriter, r *http.Request) {
		if handlerConfig.GraphiQL {
			acceptHeader := r.Header.Get("Accept")
			_, raw := r.URL.Query()["raw"]
			if !raw && !strings.Contains(acceptHeader, "application/json") && strings.Contains(acceptHeader, "text/html") {
				graphqlHandler.ServeHTTP(w, r)
				return
			}
		}
		graphqlUploadHandler.ServeHTTP(w, r)
	}

**Comment by jpascal** [comment]
@Niondir Hello! As I know, GraphiQL can't do uploads or batch requests. 

This code from one of my project and work perfectly

GoLang code:
```golang
func Execute(p graphql.Params) *graphql.Result {...}

...

http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path == "/graphql" {
		handler.New(func(request *handler.Request) interface{} {
			return Execute(graphql.Params{
				RequestString:  request.Query,
				OperationName:  request.OperationName,
				VariableValues: request.Variables,
				Schema:         gatewaySchema,
				Context:        request.Context,
			})
		}, &handler.Config{
			MaxBodySize: 1024,
		}).ServeHTTP(w, r.WithContext(r.Context()))
	} else {
		dir := http.Dir(publicDir)
		if !strings.HasPrefix(r.RequestURI, "/assets") {
			r.RequestURI = "/"
			r.URL.Path = "/"
		}
		http.FileServer(dir).ServeHTTP(w, r)
	}
}),

...
```

React code:
```tsx
<GraphiQL
    fetcher={params =>
        fetch('/graphql', {
            method: 'post',
            headers: {
                'Content-Type': 'application/json',
                [XAccessToken]: localStorage.getItem(Token),
            },
            body: JSON.stringify(params)
        }).then(response => response.json())
    }
/>
```

**Comment by niondir** [comment]
It's okay for me to not do uploads via GraphiQL but all other endpoints in the same schema need to get a GraphiQL UI during dev.
