### ISSUE TITLE
Provide documentation about what to insert in the schema and about how to read the uploaded files in the code

### ISSUE THREAD

**Issue by mjarkk** [jpascal/graphql-upload#5]
I use [graphql-go](https://github.com/graph-gophers/graphql-go) as graphql server but there is no documentation about what i should add to my schema file nor what i should add to a resolver to get the file bytes.

**Comment by jpascal** [comment]
@mjarkk Thanks! I will add some documentation about it soon.

**Comment by jpascal** [comment]
@mjarkk look inside example.go source

**Comment by mjarkk** [comment]
Thank you!
